#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=f15_flutter_env.sh
source "$ROOT/tools/f15_flutter_env.sh"
TARGET="${1:?target required}"
TMP_ROOT="${2:-$(mktemp -d "${TMPDIR:-/tmp}/electrosim-f15-${TARGET}.XXXXXX")}" 
mkdir -p "$TMP_ROOT/apps" "$TMP_ROOT/packages"
cp -R "$ROOT/apps/electrosim" "$TMP_ROOT/apps/electrosim"
for PKG in electrosim_domain electrosim_topology electrosim_solver_dc electrosim_solver_ac electrosim_controls electrosim_protection electrosim_measurement electrosim_measurements electrosim_pv electrosim_energy electrosim_canvas electrosim_ui_kit electrosim_scenarios electrosim_tp electrosim_diagnostics electrosim_storage; do
  [ -d "$ROOT/packages/$PKG" ] && cp -R "$ROOT/packages/$PKG" "$TMP_ROOT/packages/$PKG"
done
cd "$TMP_ROOT/apps/electrosim"
cp pubspec.yaml "$TMP_ROOT/pubspec.original.yaml"
"$FLUTTER_BIN" create --platforms="$TARGET" --project-name electrosim . >/dev/null
# Remove only the scaffold test generated by flutter create. The real ElectroSim tests
# come from the copied application and are preserved.
if [ -f test/widget_test.dart ] && grep -q "MyApp" test/widget_test.dart; then
  rm -f test/widget_test.dart
fi
cp "$TMP_ROOT/pubspec.original.yaml" pubspec.yaml
"$FLUTTER_BIN" pub get >&2
printf 'F15_RUNNER_PATH=%s\n' "$TMP_ROOT"
